{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

{* Current file. *}
<div class="block">
<label>{'Current file'|i18n( 'design/standard/content/datatype' )}:</label>
{section show=$attribute.content}
<table class="list" cellspacing="0">
<tr>
<th>{'Filename'|i18n( 'design/standard/content/datatype' )}</th>
<th>{'MIME type'|i18n( 'design/standard/content/datatype' )}</th>
<th>{'Size'|i18n( 'design/standard/content/datatype' )}</th>
</tr>
<tr>
<td>{$attribute.content.original_filename|wash( xhtml )}
{def $pdfviewer_url= pdfviewerurl(hash('attribute',$attribute))}
{if ne($pdfviewer_url,"")} 
{def $url_preview=concat("ezpdfviewer/do/attribute_id/",$attribute.id,"/attribute_version/",$attribute.version,"/context/edit/fullscreen/yes")}
&nbsp;->&nbsp; <a href="#" onclick="window.location.href=('{$url_preview|ezurl(no)}');" >{"preview"|i18n('ezpdfviewer/create')}</a>

{/if}
</td>
<td>{$attribute.content.mime_type|wash( xhtml )}</td>
<td>{$attribute.content.filesize|si( byte )}</td>
</tr>
</table>
{section-else}
<p>{'There is no file.'|i18n( 'design/standard/content/datatype' )}</p>
{/section}

{section show=$attribute.content}
<input class="button" type="submit" name="CustomActionButton[{$attribute.id}_delete_binary]" value="{'Remove'|i18n( 'design/standard/content/datatype' )}" title="{'Remove the file from this draft.'|i18n( 'design/standard/content/datatype' )}" />

{if eq($attribute.content.mime_type,'application/pdf' )} 

{def $url_create=concat("ezpdfviewer/do/attribute_id/",$attribute.id,"/attribute_version/",$attribute.version,"/context/edit")}

<input class="button" onclick="window.location.href='{$url_create|ezurl(no)}'" type="button" name="GenerateViewer" value="{'(Re)Generate viewer'|i18n( 'ezpdfviewer/create' )}" title="{'(Re)Generate viewer.'|i18n( 'ezpdfviewer/create' )}" />
{/if}

{undef $url_create} 
{undef $url_view} 


{section-else}
<input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_delete_binary]" value="{'Remove'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />
{/section}
</div>

{* New file. *}
<div class="block">
<label>{'New file for upload'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="hidden" name="MAX_FILE_SIZE" value="{$attribute.contentclass_attribute.data_int1}000000"/>
 {run-once}
<script>
var redirectUrl="{$attribute.object.main_node.url_alias|ezurl(no)}" ;
{literal}
function fileStore(filename,element_id){
		document.getElementById(element_id).style.display="inline";
	if(Right(filename,3)=='pdf')
	{
		alert("Please :\n 1- Store file \n 2- generate viewer");
	}
}
function Right(str, n){
    if (n <= 0)
       return "";
    else if (n > String(str).length)
       return str;
    else {
       var iLen = String(str).length;
       return String(str).substring(iLen, iLen - n);
    }
}
{/literal}
</script>
 {/run-once}
<input onchange="fileStore(this.value,'store_attribute_{$attribute.id}');" style="float:left;width:50%" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_binaryfilename_{$attribute.id}" type="file" />
<input style="display:none;float:right" id="store_attribute_{$attribute.id}" class="button" type="submit" name="StoreButton" value="{'Store'|i18n( 'design/ezwebin/content/edit' )}" />
</div>

{/default}

